export const YUKOU = 'yukou';
export const CUNZHUANG = 'cunzhuang';
export const SHANFENG = 'shanfeng';
export const ZONGJIAO = 'zongjiao';
export const JINGDIAN = 'jingdian';
export const FAGUI ='fagui';
export const JIANYI='jianyi';
export const JUBAO='jubao';
export const XINZENG='xinzeng';